FROM node:20-alpine

WORKDIR /app
COPY Frontend/package.json Frontend/package-lock.json* ./
RUN npm install

COPY Frontend/ .

ENV NEXT_TELEMETRY_DISABLED=1
EXPOSE 3000
CMD ["npm","run","dev","--","-p","3000","-H","0.0.0.0"]
