import type { Contact } from "../hooks/useContacts";

export const mockContacts: Contact[] = [
    {
        id: "1",
        name: "Srey Mom",
        email: "srey@example.com",
        subject: "Question about membership",
        message: "Hello, I would like to know how to join Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos.Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos.",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        read: false,
    },
    {
        id: "2",
        name: "John Doe",
        email: "john@example.com",
        subject: "Report issue",
        message: "I encountered a bug on the site...",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        read: true,
    },
    {
        id: "3",
        name: "Malis Chea",
        email: "malis@example.com",
        subject: "General feedback",
        message: "Great site — thanks!",
        createdAt: new Date().toISOString(),
        read: false,
    },
        {
        id: "4",
        name: "Srey Mom",
        email: "srey@example.com",
        subject: "Question about membership",
        message: "Hello, I would like to know how to join...",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        read: false,
    },
    {
        id: "5",
        name: "John Doe",
        email: "john@example.com",
        subject: "Report issue",
        message: "I encountered a bug on the site...",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        read: true,
    },
    {
        id: "6",
        name: "Malis Chea",
        email: "malis@example.com",
        subject: "General feedback",
        message: "Great site — thanks!",
        createdAt: new Date().toISOString(),
        read: false,
    },
        {
        id: "7",
        name: "Srey Mom",
        email: "srey@example.com",
        subject: "Question about membership",
        message: "Hello, I would like to know how to join...",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        read: false,
    },
    {
        id: "8",
        name: "John Doe",
        email: "john@example.com",
        subject: "Report issue",
        message: "I encountered a bug on the site...",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        read: true,
    },
    {
        id: "9",
        name: "Malis Chea",
        email: "malis@example.com",
        subject: "General feedback",
        message: "Great site — thanks!",
        createdAt: new Date().toISOString(),
        read: false,
    },
        {
        id: "10",
        name: "Srey Mom",
        email: "srey@example.com",
        subject: "Question about membership",
        message: "Hello, I would like to know how to join...",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        read: false,
    },
    {
        id: "11",
        name: "John Doe",
        email: "john@example.com",
        subject: "Report issue",
        message: "I encountered a bug on the site...",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        read: true,
    },
    {
        id: "12",
        name: "Malis Chea",
        email: "malis@example.com",
        subject: "General feedback",
        message: "Great site — thanks!",
        createdAt: new Date().toISOString(),
        read: false,
    },
];
