using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend.Migrations
{
    /// <inheritdoc />
    public partial class SeedDevRolesAndAdminData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Ensure pgcrypto available for bcrypt-style crypt()
            migrationBuilder.Sql("CREATE EXTENSION IF NOT EXISTS pgcrypto;");

            // The seed data depends on these tables existing on a fresh database.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Roles"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Name"" character varying(100) NOT NULL,
                    ""Description"" character varying(500),
                    ""IsSystemRole"" boolean NOT NULL DEFAULT false
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Roles_Name"" ON ""Roles"" (""Name"");

                CREATE TABLE IF NOT EXISTS ""Permissions"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Name"" character varying(120) NOT NULL,
                    ""Description"" character varying(500)
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Permissions_Name"" ON ""Permissions"" (""Name"");

                CREATE TABLE IF NOT EXISTS ""RolePermissions"" (
                    ""RoleId"" integer NOT NULL,
                    ""PermissionId"" integer NOT NULL,
                    CONSTRAINT ""PK_RolePermissions"" PRIMARY KEY (""RoleId"", ""PermissionId"")
                );

                CREATE INDEX IF NOT EXISTS ""IX_RolePermissions_PermissionId"" ON ""RolePermissions"" (""PermissionId"");
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_RolePermissions_Permissions_PermissionId'
                    ) THEN
                        ALTER TABLE ""RolePermissions""
                        ADD CONSTRAINT ""FK_RolePermissions_Permissions_PermissionId""
                        FOREIGN KEY (""PermissionId"") REFERENCES ""Permissions"" (""Id"") ON DELETE CASCADE;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_RolePermissions_Roles_RoleId'
                    ) THEN
                        ALTER TABLE ""RolePermissions""
                        ADD CONSTRAINT ""FK_RolePermissions_Roles_RoleId""
                        FOREIGN KEY (""RoleId"") REFERENCES ""Roles"" (""Id"") ON DELETE CASCADE;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Users""
                ADD COLUMN IF NOT EXISTS ""RoleId"" integer;

                ALTER TABLE ""Users""
                ADD COLUMN IF NOT EXISTS ""TokenValidAfter"" timestamp without time zone;

                UPDATE ""Users"" u
                SET ""RoleId"" = r.""Id""
                FROM ""Roles"" r
                WHERE u.""RoleId"" IS NULL
                  AND u.""Role"" = r.""Name"";

                UPDATE ""Users""
                SET ""RoleId"" = (
                    SELECT ""Id"" FROM ""Roles"" WHERE ""Name"" = 'User' ORDER BY ""Id"" LIMIT 1
                )
                WHERE ""RoleId"" IS NULL;

                CREATE INDEX IF NOT EXISTS ""IX_Users_RoleId"" ON ""Users"" (""RoleId"");
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_Users_Roles_RoleId'
                    ) THEN
                        ALTER TABLE ""Users""
                        ADD CONSTRAINT ""FK_Users_Roles_RoleId""
                        FOREIGN KEY (""RoleId"") REFERENCES ""Roles"" (""Id"") ON DELETE RESTRICT;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Users""
                ALTER COLUMN ""RoleId"" SET NOT NULL;
            ");

            // Insert roles if missing
            migrationBuilder.Sql(@"
                                INSERT INTO ""Roles"" (""Name"", ""IsSystemRole"", ""Description"")
                                VALUES
                                    ('User', true, 'Default user role'),
                                    ('Admin', true, 'Administrator role'),
                                    ('SuperAdmin', true, 'Super administrator')
                                ON CONFLICT (""Name"") DO NOTHING;");

            // Insert a dev admin (password hashed using pgcrypto)
            migrationBuilder.Sql(@"
                            INSERT INTO ""Users"" (""FullName"", ""Email"", ""Password"", ""IsEmailVerified"", ""RoleId"", ""Role"", ""CreatedAt"")
                            SELECT 'Admin User', 'admin@example.com', crypt('12345678', gen_salt('bf',10)), true, r.""Id"", r.""Name"", now()
                            FROM ""Roles"" r
                            WHERE r.""Name"" = 'Admin'
                            AND NOT EXISTS (SELECT 1 FROM ""Users"" u WHERE u.""Email"" = 'admin@example.com');
                        ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Remove dev admin and roles (only if they match the seeded values)
            migrationBuilder.Sql(@"
                DELETE FROM ""Users"" WHERE ""Email"" = 'admin@example.com';
                DELETE FROM ""Roles"" WHERE ""Name"" IN ('User','Admin','SuperAdmin');
            ");
        }
    }
}
